const keralaCities = [
    "Mundakayam",
    "Kanjirapally",
    "Kochi",
    "Thiruvananthapuram",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Palakkad",
    "Alappuzha",
    "Kannur",
    "Kottayam",
    "Malappuram",
    "Pathanamthitta",
    "Kasaragod",
    "Wayanad",
    "Ernakulam",
    "Idukki",
    "Trivandrum",
    "Calicut",
    "Alleppey",
    "Kovalam",
    "Munnar",
    "Thekkady",
    "Varkala",
    "Kochi Fort",
    "Kumarakom",
    "Vagamon",
    "Guruvayoor",
    "Ponmudi",
    "Marari",
    "Athirapally",
    "Mattancherry",
    "Kanhangad",
    "Vythiri",
    "Kuttanad",
    "Nilambur",
    "Payyanur",
    "Vadakara",
    "Pala",
    "Chalakudy",
    "Adoor",
    "Nedumangad",
    "Perumbavoor",
    "Paravur",
    "Nileshwar",
    "Kanur",
    "Vandiperiyar",
    "Punalur",
];



export default keralaCities;
