
//light mode
const BACKGROUND_COLOR = "black";
const BACKGROUND_COLOR_DIM = "#111111";


const BACKGROUND_COLOR_CARD = "#393646";
//LIGHT:#f2f7ff
//DARK:0b0c2a

const FORGROUND_COLOR = "white"
//LIGHT :white
//DRAK :  #16213E"
const TEXTCOLOR = "white"
const TEXTCOLOR_DIM = "#8c8db6 "



export { BACKGROUND_COLOR, FORGROUND_COLOR, TEXTCOLOR, TEXTCOLOR_DIM, BACKGROUND_COLOR_CARD, BACKGROUND_COLOR_DIM };

